# Generated by Django 6.1.1 on 2026-09-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Ingrediente',
                'verbose_name_plural': 'Categorias de Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Ingrediente')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço Adicional (R$)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ingredientes/', verbose_name='Foto do Ingrediente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriaingrediente', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
